### ISSUE TITLE
Synthetic dataset

### ISSUE THREAD

**Issue by seanli3** [lsj2408/Graphormer-GD#1]
Hi great work and an interesting paper to read.

Wondering if you are planning to release the synthetic datasets for Table 2?

**Comment by lsj2408** [comment]
Thanks for your interest in our work! The full code and synthetic dataset will be released this month soon. Please stay tuned~

**Comment by lsj2408** [comment]
Hi, I have released the synthetic dataset. Feel free to contact with us if you have any further problem.

**Comment by hcmdgh** [comment]
Hello, is the synthetic dataset in this repository?
